const data = [
  {
    Topic: "Array",
    Problem: "Reverse the array",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/",
    index: 0,
  },
  {
    Topic: "Array",
    Problem: "Find the maximum and minimum element in an array",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/",
    index: 1,
  },
  {
    Topic: "Array",
    Problem: 'Find the "Kth" max and min element of an array ',
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kth-smallest-element/0",
    index: 2,
  },
  {
    Topic: "Array",
    Problem:
      "Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0",
    index: 3,
  },
  {
    Topic: "Array",
    Problem: "Move all the negative elements to one side of the array ",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/move-negative-numbers-beginning-positive-end-constant-extra-space/",
    index: 4,
  },
  {
    Topic: "Array",
    Problem: "Find the Union and Intersection of the two sorted arrays.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/union-of-two-arrays/0",
    index: 5,
  },
  {
    Topic: "Array",
    Problem: "Write a program to cyclically rotate an array by one.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
    index: 6,
  },
  {
    Topic: "Array",
    Problem: "find Largest sum contiguous Subarray [V. IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
    index: 7,
  },
  {
    Topic: "Array",
    Problem: "Minimise the maximum difference between heights [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
    index: 8,
  },
  {
    Topic: "Array",
    Problem: "Minimum no. of Jumps to reach end of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
    index: 9,
  },
  {
    Topic: "Array",
    Problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
    index: 10,
  },
  {
    Topic: "Array",
    Problem: "Merge 2 sorted arrays without using Extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
    index: 11,
  },
  {
    Topic: "Array",
    Problem: "Kadane's Algo [V.V.V.V.V IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
    index: 12,
  },
  {
    Topic: "Array",
    Problem: "Merge Intervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
    index: 13,
  },
  {
    Topic: "Array",
    Problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
    index: 14,
  },
  {
    Topic: "Array",
    Problem: "Count Inversion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
    index: 15,
  },
  {
    Topic: "Array",
    Problem: "Best time to buy and Sell stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    index: 16,
  },
  {
    Topic: "Array",
    Problem:
      "find all pairs on integer array whose sum is equal to given number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
    index: 17,
  },
  {
    Topic: "Array",
    Problem: "find common elements In 3 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
    index: 18,
  },
  {
    Topic: "Array",
    Problem:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
    index: 19,
  },
  {
    Topic: "Array",
    Problem: "Find if there is any subarray with sum equal to 0",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
    index: 20,
  },
  {
    Topic: "Array",
    Problem: "Find factorial of a large number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
    index: 21,
  },
  {
    Topic: "Array",
    Problem: "find maximum product subarray ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
    index: 22,
  },
  {
    Topic: "Array",
    Problem: "Find longest coinsecutive subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
    index: 23,
  },
  {
    Topic: "Array",
    Problem:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
    index: 24,
  },
  {
    Topic: "Array",
    Problem: "Maximum profit by buying and selling a share atmost twice",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
    index: 25,
  },
  {
    Topic: "Array",
    Problem: "Find whether an array is a subset of another array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
    index: 26,
  },
  {
    Topic: "Array",
    Problem: "Find the triplet that sum to a given value",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0",
    index: 27,
  },
  {
    Topic: "Array",
    Problem: "Trapping Rain water problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/trapping-rain-water/0",
    index: 28,
  },
  {
    Topic: "Array",
    Problem: "Chocolate Distribution problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
    index: 29,
  },
  {
    Topic: "Array",
    Problem: "Smallest Subarray with sum greater than a given value",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/smallest-subarray-with-sum-greater-than-x/0",
    index: 30,
  },
  {
    Topic: "Array",
    Problem: "Three way partitioning of an array around a given value",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/three-way-partitioning/1",
    index: 31,
  },
  {
    Topic: "Array",
    Problem: "Minimum swaps required bring elements less equal K together",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-swaps-required-to-bring-all-elements-less-than-or-equal-to-k-together/0",
    index: 32,
  },
  {
    Topic: "Array",
    Problem: "Minimum no. of operations required to make an array palindrome",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/palindromic-array/0",
    index: 33,
  },
  {
    Topic: "Array",
    Problem: "Median of 2 sorted arrays of equal size",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-the-median0527/1",
    index: 34,
  },
  {
    Topic: "Array",
    Problem: "Median of 2 sorted arrays of different size",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays-of-different-sizes/",
    index: 35,
  },
  {
    Topic: "Matrix",
    Problem: "Spiral traversal on a Matrix",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix/0",
    index: 36,
  },
  {
    Topic: "Matrix",
    Problem: "Search an element in a matriix",
    Done: "<->",
    URL: "https://leetcode.com/problems/search-a-2d-matrix/",
    index: 37,
  },
  {
    Topic: "Matrix",
    Problem: "Find median in a row wise sorted matrix",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1",
    index: 38,
  },
  {
    Topic: "Matrix",
    Problem: "Find row with maximum no. of 1's",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1",
    index: 39,
  },
  {
    Topic: "Matrix",
    Problem:
      "Print elements in sorted order using row-column wise sorted matrix",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/sorted-matrix/0",
    index: 40,
  },
  {
    Topic: "Matrix",
    Problem: "Maximum size rectangle",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/max-rectangle/1",
    index: 41,
  },
  {
    Topic: "Matrix",
    Problem: "Find a specific pair in matrix",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-a-specific-pair-in-matrix/",
    index: 42,
  },
  {
    Topic: "Matrix",
    Problem: "Rotate matrix by 90 degrees",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/",
    index: 43,
  },
  {
    Topic: "Matrix",
    Problem: "Kth smallest element in a row-cpumn wise sorted matrix",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kth-element-in-matrix/1",
    index: 44,
  },
  {
    Topic: "Matrix",
    Problem: "Common elements in all rows of a given matrix",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/common-elements-in-all-rows-of-a-given-matrix/",
    index: 45,
  },
  {
    Topic: "String",
    Problem: "Reverse a String",
    Done: "<->",
    URL: "https://leetcode.com/problems/reverse-string/",
    index: 46,
  },
  {
    Topic: "String",
    Problem: "Check whether a String is Palindrome or not",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/palindrome-string0817/1",
    index: 47,
  },
  {
    Topic: "String",
    Problem: "Find Duplicate characters in a string",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/print-all-the-duplicates-in-the-input-string/",
    index: 48,
  },
  {
    Topic: "String",
    Problem: "Why strings are immutable in Java?",
    Done: "<->",
    URL: "<->",
    index: 49,
  },
  {
    Topic: "String",
    Problem:
      "Write a Code to check whether one string is a rotation of another",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/a-program-to-check-if-strings-are-rotations-of-each-other/",
    index: 50,
  },
  {
    Topic: "String",
    Problem:
      "Write a Program to check whether a string is a valid shuffle of two strings or not",
    Done: "<->",
    URL: "https://www.programiz.com/java-programming/examples/check-valid-shuffle-of-strings",
    index: 51,
  },
  {
    Topic: "String",
    Problem: "Count and Say problem",
    Done: "<->",
    URL: "https://leetcode.com/problems/count-and-say/",
    index: 52,
  },
  {
    Topic: "String",
    Problem:
      "Write a program to find the longest Palindrome in a string.[ Longest palindromic Substring]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-palindrome-in-a-string/0",
    index: 53,
  },
  {
    Topic: "String",
    Problem: "Find Longest Recurring Subsequence in String",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0",
    index: 54,
  },
  {
    Topic: "String",
    Problem: "Print all Subsequences of a string.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/print-subsequences-string/",
    index: 55,
  },
  {
    Topic: "String",
    Problem: "Print all the permutations of the given string",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
    index: 56,
  },
  {
    Topic: "String",
    Problem:
      "Split the Binary string into two substring with equal 0’s and 1’s",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/split-the-binary-string-into-substrings-with-equal-number-of-0s-and-1s/",
    index: 57,
  },
  {
    Topic: "String",
    Problem: "Word Wrap Problem [VERY IMP].",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/word-wrap/0",
    index: 58,
  },
  {
    Topic: "String",
    Problem: "EDIT Distance [Very Imp]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/edit-distance3702/1",
    index: 59,
  },
  {
    Topic: "String",
    Problem:
      "Find next greater number with same set of digits. [Very Very IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/next-permutation/0",
    index: 60,
  },
  {
    Topic: "String",
    Problem: "Balanced Parenthesis problem.[Imp]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
    index: 61,
  },
  {
    Topic: "String",
    Problem: "Word break Problem[ Very Imp]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/word-break/0",
    index: 62,
  },
  {
    Topic: "String",
    Problem: "Rabin Karp Algo",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/",
    index: 63,
  },
  {
    Topic: "String",
    Problem: "KMP Algo",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-prefix-suffix2527/1",
    index: 64,
  },
  {
    Topic: "String",
    Problem:
      "Convert a Sentence into its equivalent mobile numeric keypad sequence.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/convert-sentence-equivalent-mobile-numeric-keypad-sequence/",
    index: 65,
  },
  {
    Topic: "String",
    Problem:
      "Minimum number of bracket reversals needed to make an expression balanced.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-the-reversals/0",
    index: 66,
  },
  {
    Topic: "String",
    Problem: "Count All Palindromic Subsequence in a given String.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1",
    index: 67,
  },
  {
    Topic: "String",
    Problem: "Count of number of given string in 2D character array",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-count-number-given-string-present-2d-character-array/",
    index: 68,
  },
  {
    Topic: "String",
    Problem: "Search a Word in a 2D Grid of characters.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-the-string-in-grid/0",
    index: 69,
  },
  {
    Topic: "String",
    Problem: "Boyer Moore Algorithm for Pattern Searching.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/boyer-moore-algorithm-for-pattern-searching/",
    index: 70,
  },
  {
    Topic: "String",
    Problem: "Converting Roman Numerals to Decimal",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/roman-number-to-integer/0",
    index: 71,
  },
  {
    Topic: "String",
    Problem: "Longest Common Prefix",
    Done: "<->",
    URL: "https://leetcode.com/problems/longest-common-prefix/",
    index: 72,
  },
  {
    Topic: "String",
    Problem: "Number of flips to make binary string alternate",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/min-number-of-flips/0",
    index: 73,
  },
  {
    Topic: "String",
    Problem: "Find the first repeated word in string.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/second-most-repeated-string-in-a-sequence/0",
    index: 74,
  },
  {
    Topic: "String",
    Problem: "Minimum number of swaps for bracket balancing.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-swaps-for-bracket-balancing/0",
    index: 75,
  },
  {
    Topic: "String",
    Problem: "Find the longest common subsequence between two strings.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
    index: 76,
  },
  {
    Topic: "String",
    Problem:
      "Program to generate all possible valid IP addresses from given  string.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/program-generate-possible-valid-ip-addresses-given-string/",
    index: 77,
  },
  {
    Topic: "String",
    Problem:
      "Write a program to find the smallest window that contains all characters of string itself.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/smallest-distant-window/0",
    index: 78,
  },
  {
    Topic: "String",
    Problem:
      "Rearrange characters in a string such that no two adjacent are same",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0",
    index: 79,
  },
  {
    Topic: "String",
    Problem:
      "Minimum characters to be added at front to make string palindrome",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/",
    index: 80,
  },
  {
    Topic: "String",
    Problem: "Given a sequence of words, print all anagrams together",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0",
    index: 81,
  },
  {
    Topic: "String",
    Problem:
      "Find the smallest window in a string containing all characters of another string",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string/0",
    index: 82,
  },
  {
    Topic: "String",
    Problem: "Recursively remove all adjacent duplicates",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/consecutive-elements/0",
    index: 83,
  },
  {
    Topic: "String",
    Problem: "String matching where one string contains wildcard characters",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/wildcard-string-matching/0",
    index: 84,
  },
  {
    Topic: "String",
    Problem:
      "Function to find Number of customers who could not get a computer",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/function-to-find-number-of-customers-who-could-not-get-a-computer/",
    index: 85,
  },
  {
    Topic: "String",
    Problem:
      "Transform One String to Another using Minimum Number of Given Operation",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/transform-one-string-to-another-using-minimum-number-of-given-operation/",
    index: 86,
  },
  {
    Topic: "String",
    Problem: "Check if two given strings are isomorphic to each other",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/isomorphic-strings/0",
    index: 87,
  },
  {
    Topic: "String",
    Problem:
      "Recursively print all sentences that can be formed from list of word lists",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/recursively-print-all-sentences-that-can-be-formed-from-list-of-word-lists/",
    index: 88,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Find first and last positions of an element in a sorted array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/first-and-last-occurrences-of-x/0",
    index: 89,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Find a Fixed Point (Value equal to index) in a given array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/value-equal-to-index-value1330/1",
    index: 90,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Search in a rotated sorted array",
    Done: "<->",
    URL: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    index: 91,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "square root of an integer",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-squares3649/1",
    index: 92,
  },
  {
    Topic: "Searching & Sorting",
    Problem:
      "Maximum and minimum of an array using minimum number of comparisons",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/middle-of-three2926/1",
    index: 93,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Optimum location of point to minimize total distance",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/optimum-location-point-minimize-total-distance/",
    index: 94,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Find the repeating and the missing",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating2512/1",
    index: 95,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "find majority element",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/majority-element/0",
    index: 96,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Searching in an array where adjacent differ by at most k",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/searching-array-adjacent-differ-k/",
    index: 97,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "find a pair with a given difference",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-pair-given-difference/0",
    index: 98,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "find four elements that sum to a given value",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-all-four-sum-numbers/0",
    index: 99,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "maximum sum such that no 2 elements are adjacent",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/stickler-theif/0",
    index: 100,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Count triplet with sum smaller than a given value",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-triplets-with-sum-smaller-than-x5549/1",
    index: 101,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "merge 2 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
    index: 102,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "print all subarrays with 0 sum",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/zero-sum-subarrays/0",
    index: 103,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Product array Puzzle",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/product-array-puzzle/0",
    index: 104,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Sort array according to count of set bits",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/sort-by-set-bit-count/0",
    index: 105,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "minimum no. of swaps required to sort the array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-swaps/1",
    index: 106,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Bishu and Soldiers",
    Done: "<->",
    URL: "https://www.hackerearth.com/practice/algorithms/searching/binary-search/practice-problems/algorithm/bishu-and-soldiers/",
    index: 107,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Rasta and Kheshtak",
    Done: "<->",
    URL: "https://www.hackerearth.com/practice/algorithms/searching/binary-search/practice-problems/algorithm/rasta-and-kheshtak/",
    index: 108,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Kth smallest number again",
    Done: "<->",
    URL: "https://www.hackerearth.com/practice/algorithms/searching/binary-search/practice-problems/algorithm/kth-smallest-number-again-2/",
    index: 109,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Find pivot element in a sorted array",
    Done: "<->",
    URL: "http://theoryofprogramming.com/2017/12/16/find-pivot-element-sorted-rotated-array/",
    index: 110,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "K-th Element of Two Sorted Arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array/0",
    index: 111,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Aggressive cows",
    Done: "<->",
    URL: "https://www.spoj.com/problems/AGGRCOW/",
    index: 112,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Book Allocation Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages/0",
    index: 113,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "EKOSPOJ:",
    Done: "<->",
    URL: "https://www.spoj.com/problems/EKO/",
    index: 114,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Job Scheduling Algo",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/weighted-job-scheduling-log-n-time/",
    index: 115,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Missing Number in AP",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/arithmetic-number/0",
    index: 116,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Smallest number with atleastn trailing zeroes infactorial",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/smallest-factorial-number5929/1",
    index: 117,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Painters Partition Problem:",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages/0",
    index: 118,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "ROTI-Prata SPOJ",
    Done: "<->",
    URL: "https://www.spoj.com/problems/PRATA/",
    index: 119,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "DoubleHelix SPOJ",
    Done: "<->",
    URL: "https://www.spoj.com/problems/ANARC05B/",
    index: 120,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Subset Sums",
    Done: "<->",
    URL: "https://www.spoj.com/problems/SUBSUMS/",
    index: 121,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Findthe inversion count",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
    index: 122,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Implement Merge-sort in-place",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/in-place-merge-sort/",
    index: 123,
  },
  {
    Topic: "Searching & Sorting",
    Problem: "Partitioning and Sorting Arrays with Many Repeated Entries",
    Done: "<->",
    URL: "https://www.baeldung.com/java-sorting-arrays-with-repeated-entries",
    index: 124,
  },
  {
    Topic: "LinkedList",
    Problem:
      "Write a Program to reverse the Linked List. (Both Iterative and recursive)",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/reverse-a-linked-list/",
    index: 125,
  },
  {
    Topic: "LinkedList",
    Problem: "Reverse a Linked List in group of Given Size. [Very Imp]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1",
    index: 126,
  },
  {
    Topic: "LinkedList",
    Problem: "Write a program to Detect loop in a linked list.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
    index: 127,
  },
  {
    Topic: "LinkedList",
    Problem: "Write a program to Delete loop in a linked list.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1",
    index: 128,
  },
  {
    Topic: "LinkedList",
    Problem: "Find the starting point of the loop. ",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-first-node-of-loop-in-a-linked-list/",
    index: 129,
  },
  {
    Topic: "LinkedList",
    Problem: "Remove Duplicates in a sorted Linked List.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1",
    index: 130,
  },
  {
    Topic: "LinkedList",
    Problem: "Remove Duplicates in a Un-sorted Linked List.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/remove-duplicates-from-an-unsorted-linked-list/1",
    index: 131,
  },
  {
    Topic: "LinkedList",
    Problem:
      "Write a Program to Move the last element to Front in a Linked List.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/move-last-element-to-front-of-a-given-linked-list/",
    index: 132,
  },
  {
    Topic: "LinkedList",
    Problem: "Add “1” to a number represented as a Linked List.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1",
    index: 133,
  },
  {
    Topic: "LinkedList",
    Problem: "Add two numbers represented by linked lists.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1",
    index: 134,
  },
  {
    Topic: "LinkedList",
    Problem: "Intersection of two Sorted Linked List.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/intersection-of-two-sorted-linked-lists/1",
    index: 135,
  },
  {
    Topic: "LinkedList",
    Problem: "Intersection Point of two Linked Lists.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1",
    index: 136,
  },
  {
    Topic: "LinkedList",
    Problem: "Merge Sort For Linked lists.[Very Important]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1",
    index: 137,
  },
  {
    Topic: "LinkedList",
    Problem: "Quicksort for Linked Lists.[Very Important]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/quick-sort-on-linked-list/1",
    index: 138,
  },
  {
    Topic: "LinkedList",
    Problem: "Find the middle Element of a linked list.",
    Done: "<->",
    URL: "https://leetcode.com/problems/middle-of-the-linked-list/",
    index: 139,
  },
  {
    Topic: "LinkedList",
    Problem: "Check if a linked list is a circular linked list.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/circular-linked-list/1",
    index: 140,
  },
  {
    Topic: "LinkedList",
    Problem: "Split a Circular linked list into two halves.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/split-a-circular-linked-list-into-two-halves/1",
    index: 141,
  },
  {
    Topic: "LinkedList",
    Problem:
      "Write a Program to check whether the Singly Linked list is a palindrome or not.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1",
    index: 142,
  },
  {
    Topic: "LinkedList",
    Problem: "Deletion from a Circular Linked List.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/deletion-circular-linked-list/",
    index: 143,
  },
  {
    Topic: "LinkedList",
    Problem: "Reverse a Doubly Linked list.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/reverse-a-doubly-linked-list/1",
    index: 144,
  },
  {
    Topic: "LinkedList",
    Problem: "Find pairs with a given sum in a DLL.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-pairs-given-sum-doubly-linked-list/",
    index: 145,
  },
  {
    Topic: "LinkedList",
    Problem:
      "Count triplets in a sorted DLL whose sum is equal to given value “X”.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/count-triplets-sorted-doubly-linked-list-whose-sum-equal-given-value-x/",
    index: 146,
  },
  {
    Topic: "LinkedList",
    Problem: "Sort a “k”sorted Doubly Linked list.[Very IMP]",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/sort-k-sorted-doubly-linked-list/",
    index: 147,
  },
  {
    Topic: "LinkedList",
    Problem: "Rotate DoublyLinked list by N nodes.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rotate-doubly-linked-list-n-nodes/",
    index: 148,
  },
  {
    Topic: "LinkedList",
    Problem: "Rotate a Doubly Linked list in group of Given Size.[Very IMP]",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/reverse-doubly-linked-list-groups-given-size/",
    index: 149,
  },
  {
    Topic: "LinkedList",
    Problem: "Can we reverse a linked list in less than O(n) ?",
    Done: "<->",
    URL: "<->",
    index: 150,
  },
  {
    Topic: "LinkedList",
    Problem:
      "Why Quicksort is preferred for. Arrays and Merge Sort for LinkedLists ?",
    Done: "<->",
    URL: "<->",
    index: 151,
  },
  {
    Topic: "LinkedList",
    Problem: "Flatten a Linked List",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
    index: 152,
  },
  {
    Topic: "LinkedList",
    Problem: "Sort a LL of 0's, 1's and 2's",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/given-a-linked-list-of-0s-1s-and-2s-sort-it/1",
    index: 153,
  },
  {
    Topic: "LinkedList",
    Problem: "Clone a linked list with next and random pointer",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1",
    index: 154,
  },
  {
    Topic: "LinkedList",
    Problem: "Merge K sorted Linked list",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1",
    index: 155,
  },
  {
    Topic: "LinkedList",
    Problem: "Multiply 2 no. represented by LL",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/multiply-two-linked-lists/1",
    index: 156,
  },
  {
    Topic: "LinkedList",
    Problem: "Delete nodes which have a greater value on right side",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/delete-nodes-having-greater-value-on-right/1",
    index: 157,
  },
  {
    Topic: "LinkedList",
    Problem: "Segregate even and odd nodes in a Linked List",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/segregate-even-and-odd-nodes-in-a-linked-list/0",
    index: 158,
  },
  {
    Topic: "LinkedList",
    Problem: "Program for n’th node from the end of a Linked List",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1",
    index: 159,
  },
  {
    Topic: "LinkedList",
    Problem:
      "Find the first non-repeating character from a stream of characters",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0",
    index: 160,
  },
  {
    Topic: "Binary Trees",
    Problem: "level order traversal",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/level-order-traversal/1",
    index: 161,
  },
  {
    Topic: "Binary Trees",
    Problem: "Reverse Level Order traversal",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/reverse-level-order-traversal/1",
    index: 162,
  },
  {
    Topic: "Binary Trees",
    Problem: "Height of a tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1",
    index: 163,
  },
  {
    Topic: "Binary Trees",
    Problem: "Diameter of a tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1",
    index: 164,
  },
  {
    Topic: "Binary Trees",
    Problem: "Mirror of a tree",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/create-a-mirror-tree-from-the-given-binary-tree/",
    index: 165,
  },
  {
    Topic: "Binary Trees",
    Problem: "Inorder Traversal of a tree both using recursion and Iteration",
    Done: "<->",
    URL: "https://www.techiedelight.com/inorder-tree-traversal-iterative-recursive/",
    index: 166,
  },
  {
    Topic: "Binary Trees",
    Problem: "Preorder Traversal of a tree both using recursion and Iteration",
    Done: "<->",
    URL: "https://www.techiedelight.com/preorder-tree-traversal-iterative-recursive/",
    index: 167,
  },
  {
    Topic: "Binary Trees",
    Problem: "Postorder Traversal of a tree both using recursion and Iteration",
    Done: "<->",
    URL: "https://www.techiedelight.com/postorder-tree-traversal-iterative-recursive/",
    index: 168,
  },
  {
    Topic: "Binary Trees",
    Problem: "Left View of a tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
    index: 169,
  },
  {
    Topic: "Binary Trees",
    Problem: "Right View of Tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/right-view-of-binary-tree/1",
    index: 170,
  },
  {
    Topic: "Binary Trees",
    Problem: "Top View of a tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1",
    index: 171,
  },
  {
    Topic: "Binary Trees",
    Problem: "Bottom View of a tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1",
    index: 172,
  },
  {
    Topic: "Binary Trees",
    Problem: "Zig-Zag traversal of a binary tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/zigzag-tree-traversal/1",
    index: 173,
  },
  {
    Topic: "Binary Trees",
    Problem: "Check if a tree is balanced or not",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/check-for-balanced-tree/1",
    index: 174,
  },
  {
    Topic: "Binary Trees",
    Problem: "Diagonal Traversal of a Binary tree",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/diagonal-traversal-of-binary-tree/",
    index: 175,
  },
  {
    Topic: "Binary Trees",
    Problem: "Boundary traversal of a Binary tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1",
    index: 176,
  },
  {
    Topic: "Binary Trees",
    Problem: "Construct Binary Tree from String with Bracket Representation",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/construct-binary-tree-string-bracket-representation/",
    index: 177,
  },
  {
    Topic: "Binary Trees",
    Problem: "Convert Binary tree into Doubly Linked List",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/binary-tree-to-dll/1",
    index: 178,
  },
  {
    Topic: "Binary Trees",
    Problem: "Convert Binary tree into Sum tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/transform-to-sum-tree/1",
    index: 179,
  },
  {
    Topic: "Binary Trees",
    Problem: "Construct Binary tree from Inorder and preorder traversal",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/construct-tree-1/1",
    index: 180,
  },
  {
    Topic: "Binary Trees",
    Problem: "Find minimum swaps required to convert a Binary tree into BST",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimum-swap-required-convert-binary-tree-binary-search-tree/",
    index: 181,
  },
  {
    Topic: "Binary Trees",
    Problem: "Check if Binary tree is Sum tree or not",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/sum-tree/1",
    index: 182,
  },
  {
    Topic: "Binary Trees",
    Problem: "Check if all leaf nodes are at same level or not",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/leaf-at-same-level/1",
    index: 183,
  },
  {
    Topic: "Binary Trees",
    Problem:
      "Check if a Binary Tree contains duplicate subtrees of size 2 or more [ IMP ]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/duplicate-subtree-in-binary-tree/1",
    index: 184,
  },
  {
    Topic: "Binary Trees",
    Problem: "Check if 2 trees are mirror or not",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/check-mirror-in-n-ary-tree/0",
    index: 185,
  },
  {
    Topic: "Binary Trees",
    Problem: "Sum of Nodes on the Longest path from root to leaf node ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/sum-of-the-longest-bloodline-of-a-tree/1",
    index: 186,
  },
  {
    Topic: "Binary Trees",
    Problem: "Check if given graph is tree or not.  [ IMP ]",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/check-given-graph-tree/",
    index: 187,
  },
  {
    Topic: "Binary Trees",
    Problem: "Find Largest subtree sum in a tree",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-largest-subtree-sum-tree/",
    index: 188,
  },
  {
    Topic: "Binary Trees",
    Problem:
      "Maximum Sum of nodes in Binary tree such that no two are adjacent ",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-sum-nodes-binary-tree-no-two-adjacent/",
    index: 189,
  },
  {
    Topic: "Binary Trees",
    Problem: 'Print all "K" Sum paths in a Binary tree',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/print-k-sum-paths-binary-tree/",
    index: 190,
  },
  {
    Topic: "Binary Trees",
    Problem: "Find LCA in a Binary tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1",
    index: 191,
  },
  {
    Topic: "Binary Trees",
    Problem: "Find distance between 2 nodes in a Binary tree",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/min-distance-between-two-given-nodes-of-a-binary-tree/1",
    index: 192,
  },
  {
    Topic: "Binary Trees",
    Problem: "Kth Ancestor of node in a Binary tree",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/kth-ancestor-node-binary-tree-set-2/",
    index: 193,
  },
  {
    Topic: "Binary Trees",
    Problem: "Find all Duplicate subtrees in a Binary tree [ IMP ]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/duplicate-subtrees/1",
    index: 194,
  },
  {
    Topic: "Binary Trees",
    Problem: "Tree Isomorphism Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/check-if-tree-is-isomorphic/1",
    index: 195,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Fina a value in a BST",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/binary-search-tree-set-1-search-and-insertion/",
    index: 196,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Deletion of a node in a BST",
    Done: "<->",
    URL: "https://leetcode.com/problems/delete-node-in-a-bst/",
    index: 197,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Find min and max value in a BST",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-element-in-bst/1",
    index: 198,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Find inorder successor and inorder predecessor in a BST",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1",
    index: 199,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Check if a tree is a BST or not ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/check-for-bst/1",
    index: 200,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Populate Inorder successor of all nodes",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/populate-inorder-successor-for-all-nodes/1",
    index: 201,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Find LCA  of 2 nodes in a BST",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1",
    index: 202,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Construct BST from preorder traversal",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/construct-bst-from-given-preorder-traversa/",
    index: 203,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Convert Binary tree into BST",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/binary-tree-to-bst/1",
    index: 204,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Convert a normal BST into a Balanced BST",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/convert-normal-bst-balanced-bst/",
    index: 205,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Merge two BST [ V.V.V>IMP ]",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/merge-two-balanced-binary-search-trees/",
    index: 206,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Find Kth largest element in a BST",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kth-largest-element-in-bst/1",
    index: 207,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Find Kth smallest element in a BST",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-k-th-smallest-element-in-bst/1",
    index: 208,
  },
  {
    Topic: "Binary Search Trees",
    Problem: 'Count pairs from 2 BST whose sum is equal to given value "X"',
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/brothers-from-different-root/1",
    index: 209,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Find the median of BST in O(n) time and O(1) space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-median-bst-time-o1-space/",
    index: 210,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Count BST ndoes that lie in a given range",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-bst-nodes-that-lie-in-a-given-range/1",
    index: 211,
  },
  {
    Topic: "Binary Search Trees",
    Problem:
      "Replace every element with the least greater element on its right",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/replace-every-element-with-the-least-greater-element-on-its-right/",
    index: 212,
  },
  {
    Topic: "Binary Search Trees",
    Problem: 'Given "n" appointments, find the conflicting appointments',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-n-appointments-find-conflicting-appointments/",
    index: 213,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Check preorder is valid or not",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/preorder-to-postorder/0",
    index: 214,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Check whether BST contains Dead end",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/check-whether-bst-contains-dead-end/1",
    index: 215,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Largest BST in a Binary Tree [ V.V.V.V.V IMP ]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/largest-bst/1",
    index: 216,
  },
  {
    Topic: "Binary Search Trees",
    Problem: "Flatten BST to sorted list",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/flatten-bst-to-sorted-list-increasing-order/",
    index: 217,
  },
  {
    Topic: "Greedy",
    Problem: "Activity Selection Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room/0",
    index: 218,
  },
  {
    Topic: "Greedy",
    Problem: "Job SequencingProblem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem/0",
    index: 219,
  },
  {
    Topic: "Greedy",
    Problem: "Huffman Coding",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/huffman-encoding/0",
    index: 220,
  },
  {
    Topic: "Greedy",
    Problem: "Water Connection Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/water-connection-problem/0",
    index: 221,
  },
  {
    Topic: "Greedy",
    Problem: "Fractional Knapsack Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/fractional-knapsack/0",
    index: 222,
  },
  {
    Topic: "Greedy",
    Problem: "Greedy Algorithm to find Minimum number of Coins",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/coin-piles/0",
    index: 223,
  },
  {
    Topic: "Greedy",
    Problem: "Maximum trains for which stoppage can be provided",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-trains-stoppage-can-provided/",
    index: 224,
  },
  {
    Topic: "Greedy",
    Problem: "Minimum Platforms Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-platforms/0",
    index: 225,
  },
  {
    Topic: "Greedy",
    Problem: "Buy Maximum Stocks if i stocks can be bought on i-th day",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/buy-maximum-stocks-stocks-can-bought-th-day/",
    index: 226,
  },
  {
    Topic: "Greedy",
    Problem: "Find the minimum and maximum amount to buy all N candies",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/shop-in-candy-store/0",
    index: 227,
  },
  {
    Topic: "Greedy",
    Problem:
      "Minimize Cash Flow among a given set of friends who have borrowed money from each other",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/",
    index: 228,
  },
  {
    Topic: "Greedy",
    Problem: "Minimum Cost to cut a board into squares",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimum-cost-cut-board-squares/",
    index: 229,
  },
  {
    Topic: "Greedy",
    Problem: "Check if it is possible to survive on Island",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/survival/",
    index: 230,
  },
  {
    Topic: "Greedy",
    Problem: "Find maximum meetings in one room",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-maximum-meetings-in-one-room/",
    index: 231,
  },
  {
    Topic: "Greedy",
    Problem: "Maximum product subset of an array",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-product-subset-array/",
    index: 232,
  },
  {
    Topic: "Greedy",
    Problem: "Maximize array sum after K negations",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximize-sum-after-k-negations/0",
    index: 233,
  },
  {
    Topic: "Greedy",
    Problem: "Maximize the sum of arr[i]*i",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximize-arrii-of-an-array/0",
    index: 234,
  },
  {
    Topic: "Greedy",
    Problem: "Maximum sum of absolute difference of an array",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-sum-absolute-difference-array/",
    index: 235,
  },
  {
    Topic: "Greedy",
    Problem: "Maximize sum of consecutive differences in a circular array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/swap-and-maximize/0",
    index: 236,
  },
  {
    Topic: "Greedy",
    Problem: "Minimum sum of absolute difference of pairs of two arrays",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimum-sum-absolute-difference-pairs-two-arrays/",
    index: 237,
  },
  {
    Topic: "Greedy",
    Problem: "Program for Shortest Job First (or SJF) CPU Scheduling",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/program-for-shortest-job-first-or-sjf-cpu-scheduling-set-1-non-preemptive/",
    index: 238,
  },
  {
    Topic: "Greedy",
    Problem: "Program for Least Recently Used (LRU) Page Replacement algorithm",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/page-faults-in-lru/0",
    index: 239,
  },
  {
    Topic: "Greedy",
    Problem: "Smallest subset with sum greater than all other elements",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/smallest-subset-sum-greater-elements/",
    index: 240,
  },
  {
    Topic: "Greedy",
    Problem: "Chocolate Distribution Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
    index: 241,
  },
  {
    Topic: "Greedy",
    Problem: "DEFKIN -Defense of a Kingdom",
    Done: "<->",
    URL: "https://www.spoj.com/problems/DEFKIN/",
    index: 242,
  },
  {
    Topic: "Greedy",
    Problem: "DIEHARD -DIE HARD",
    Done: "<->",
    URL: "https://www.spoj.com/problems/DIEHARD/",
    index: 243,
  },
  {
    Topic: "Greedy",
    Problem: "GERGOVIA -Wine trading in Gergovia",
    Done: "<->",
    URL: "https://www.spoj.com/problems/GERGOVIA/",
    index: 244,
  },
  {
    Topic: "Greedy",
    Problem: "Picking Up Chicks",
    Done: "<->",
    URL: "https://www.spoj.com/problems/GCJ101BB/",
    index: 245,
  },
  {
    Topic: "Greedy",
    Problem: "CHOCOLA –Chocolate",
    Done: "<->",
    URL: "https://www.spoj.com/problems/CHOCOLA/",
    index: 246,
  },
  {
    Topic: "Greedy",
    Problem: "ARRANGE -Arranging Amplifiers",
    Done: "<->",
    URL: "https://www.spoj.com/problems/ARRANGE/",
    index: 247,
  },
  {
    Topic: "Greedy",
    Problem: "K Centers Problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/k-centers-problem-set-1-greedy-approximate-algorithm/",
    index: 248,
  },
  {
    Topic: "Greedy",
    Problem: "Minimum Cost of ropes",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes/0",
    index: 249,
  },
  {
    Topic: "Greedy",
    Problem:
      "Find smallest number with given number of digits and sum of digits",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/smallest-number5829/1",
    index: 250,
  },
  {
    Topic: "Greedy",
    Problem:
      "Rearrange characters in a string such that no two adjacent are same",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0",
    index: 251,
  },
  {
    Topic: "Greedy",
    Problem: "Find maximum sum possible equal sum of three stacks",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-maximum-sum-possible-equal-sum-three-stacks/",
    index: 252,
  },
  {
    Topic: "BackTracking",
    Problem: "Rat in a maze Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
    index: 253,
  },
  {
    Topic: "BackTracking",
    Problem: "Printing all solutions in N-Queen Problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/printing-solutions-n-queen-problem/",
    index: 254,
  },
  {
    Topic: "BackTracking",
    Problem: "Word Break Problem using Backtracking",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/word-break-part-2/0",
    index: 255,
  },
  {
    Topic: "BackTracking",
    Problem: "Remove Invalid Parentheses",
    Done: "<->",
    URL: "https://leetcode.com/problems/remove-invalid-parentheses/",
    index: 256,
  },
  {
    Topic: "BackTracking",
    Problem: "Sudoku Solver",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/solve-the-sudoku/0",
    index: 257,
  },
  {
    Topic: "BackTracking",
    Problem: "m Coloring Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/m-coloring-problem/0",
    index: 258,
  },
  {
    Topic: "BackTracking",
    Problem: "Print all palindromic partitions of a string",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-a-string-print-all-possible-palindromic-partition/",
    index: 259,
  },
  {
    Topic: "BackTracking",
    Problem: "Subset Sum Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1",
    index: 260,
  },
  {
    Topic: "BackTracking",
    Problem: "The Knight’s tour problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/the-knights-tour-problem-backtracking-1/",
    index: 261,
  },
  {
    Topic: "BackTracking",
    Problem: "Tug of War",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/tug-of-war/",
    index: 262,
  },
  {
    Topic: "BackTracking",
    Problem: "Find shortest safe route in a path with landmines",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-shortest-safe-route-in-a-path-with-landmines/",
    index: 263,
  },
  {
    Topic: "BackTracking",
    Problem: "Combinational Sum",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/combination-sum/0",
    index: 264,
  },
  {
    Topic: "BackTracking",
    Problem: "Find Maximum number possible by doing at-most K swaps",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/largest-number-in-k-swaps/0",
    index: 265,
  },
  {
    Topic: "BackTracking",
    Problem: "Print all permutations of a string ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0",
    index: 266,
  },
  {
    Topic: "BackTracking",
    Problem: "Find if there is a path of more than k length from a source",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/",
    index: 267,
  },
  {
    Topic: "BackTracking",
    Problem: "Longest Possible Route in a Matrix with Hurdles",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/longest-possible-route-in-a-matrix-with-hurdles/",
    index: 268,
  },
  {
    Topic: "BackTracking",
    Problem:
      "Print all possible paths from top left to bottom right of a mXn matrix",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/print-all-possible-paths-from-top-left-to-bottom-right-of-a-mxn-matrix/",
    index: 269,
  },
  {
    Topic: "BackTracking",
    Problem: "Partition of a set intoK subsets with equal sum",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/partition-array-to-k-subsets/1",
    index: 270,
  },
  {
    Topic: "BackTracking",
    Problem: "Find the K-th Permutation Sequence of first N natural numbers",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-the-k-th-permutation-sequence-of-first-n-natural-numbers/",
    index: 271,
  },
  {
    Topic: "Stacks & Queues",
    Problem: " Implement Stack from Scratch",
    Done: "<->",
    URL: "https://www.tutorialspoint.com/javaexamples/data_stack.htm",
    index: 272,
  },
  {
    Topic: "Stacks & Queues",
    Problem: " Implement Queue from Scratch",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/",
    index: 273,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Implement 2 stack in an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1",
    index: 274,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "find the middle element of a stack",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/design-a-stack-with-find-middle-operation/",
    index: 275,
  },
  {
    Topic: "Stacks & Queues",
    Problem: 'Implement "N" stacks in an Array',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/efficiently-implement-k-stacks-single-array/",
    index: 276,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Check the expression has valid or Balanced parenthesis or not.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0",
    index: 277,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Reverse a String using Stack",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/reverse-a-string-using-stack/1",
    index: 278,
  },
  {
    Topic: "Stacks & Queues",
    Problem:
      "Design a Stack that supports getMin() in O(1) time and O(1) extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/special-stack/1",
    index: 279,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Find the next Greater element",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/next-larger-element/0",
    index: 280,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "The celebrity Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1",
    index: 281,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Arithmetic Expression evaluation",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/arithmetic-expression-evalution/",
    index: 282,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Evaluation of Postfix expression",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/evaluation-of-postfix-expression/0",
    index: 283,
  },
  {
    Topic: "Stacks & Queues",
    Problem:
      "Implement a method to insert an element at its bottom without using any other data structure.",
    Done: "<->",
    URL: "https://stackoverflow.com/questions/45130465/inserting-at-the-end-of-stack",
    index: 284,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Reverse a stack using recursion",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/reverse-a-stack-using-recursion/",
    index: 285,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Sort a Stack using recursion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/sort-a-stack/1",
    index: 286,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Merge Overlapping Intervals",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/overlapping-intervals/0",
    index: 287,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Largest rectangular Area in Histogram",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram/0",
    index: 288,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Length of the Longest Valid Substring",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/valid-substring0624/1",
    index: 289,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Expression contains redundant bracket or not",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/expression-contains-redundant-bracket-not/",
    index: 290,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Implement Stack using Queue",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1",
    index: 291,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Implement Stack using Deque",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/implement-stack-queue-using-deque/",
    index: 292,
  },
  {
    Topic: "Stacks & Queues",
    Problem:
      "Stack Permutations (Check if an array is stack permutation of other)",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/stack-permutations-check-if-an-array-is-stack-permutation-of-other/",
    index: 293,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Implement Queue using Stack  ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1",
    index: 294,
  },
  {
    Topic: "Stacks & Queues",
    Problem: 'Implement "n" queue in an array',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/efficiently-implement-k-queues-single-array/",
    index: 295,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Implement a Circular queue",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/circular-queue-set-1-introduction-array-implementation/",
    index: 296,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "LRU Cache Implementationa",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/lru-cache/1",
    index: 297,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Reverse a Queue using recursion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/queue-reversal/1",
    index: 298,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Reverse the first “K” elements of a queue",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1",
    index: 299,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Interleave the first half of the queue with second half",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/interleave-first-half-queue-second-half/",
    index: 300,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Find the first circular tour that visits all Petrol Pumps",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/circular-tour/1",
    index: 301,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Minimum time required to rot all oranges",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/rotten-oranges/0",
    index: 302,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Distance of nearest cell having 1 in a binary matrix",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/distance-of-nearest-cell-having-1/0",
    index: 303,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "First negative integer in every window of size “k”",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/first-negative-integer-in-every-window-of-size-k/0",
    index: 304,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Check if all levels of two trees are anagrams or not.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/check-if-all-levels-of-two-trees-are-anagrams-or-not/",
    index: 305,
  },
  {
    Topic: "Stacks & Queues",
    Problem:
      "Sum of minimum and maximum elements of all subarrays of size “k”.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/sum-minimum-maximum-elements-subarrays-size-k/",
    index: 306,
  },
  {
    Topic: "Stacks & Queues",
    Problem:
      "Minimum sum of squares of character counts in a given string after removing “k” characters.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/game-with-string/0",
    index: 307,
  },
  {
    Topic: "Stacks & Queues",
    Problem:
      "Queue based approach or first non-repeating character in a stream.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0",
    index: 308,
  },
  {
    Topic: "Stacks & Queues",
    Problem: "Next Smaller Element",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/next-smaller-element/",
    index: 309,
  },
  {
    Topic: "Heap",
    Problem: "Implement a Maxheap/MinHeap using arrays and recursion.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/building-heap-from-array/",
    index: 310,
  },
  {
    Topic: "Heap",
    Problem: "Sort an Array using heap. (HeapSort)",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/heap-sort/",
    index: 311,
  },
  {
    Topic: "Heap",
    Problem: "Maximum of all subarrays of size k.",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/",
    index: 312,
  },
  {
    Topic: "Heap",
    Problem: "“k” largest element in an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/k-largest-elements4206/1",
    index: 313,
  },
  {
    Topic: "Heap",
    Problem: "Kth smallest and largest element in an unsorted array",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/",
    index: 314,
  },
  {
    Topic: "Heap",
    Problem: "Merge “K” sorted arrays. [ IMP ]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-arrays/1",
    index: 315,
  },
  {
    Topic: "Heap",
    Problem: "Merge 2 Binary Max Heaps",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-binary-max-heap/0",
    index: 316,
  },
  {
    Topic: "Heap",
    Problem: "Kth largest sum continuous subarrays",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/k-th-largest-sum-contiguous-subarray/",
    index: 317,
  },
  {
    Topic: "Heap",
    Problem: "Leetcode- reorganize strings",
    Done: "<->",
    URL: "https://leetcode.com/problems/reorganize-string/",
    index: 318,
  },
  {
    Topic: "Heap",
    Problem: "Merge “K” Sorted Linked Lists [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1",
    index: 319,
  },
  {
    Topic: "Heap",
    Problem: "Smallest range in “K” Lists",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-smallest-range-containing-elements-from-k-lists/1",
    index: 320,
  },
  {
    Topic: "Heap",
    Problem: "Median in a stream of Integers",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-median-in-a-stream/0",
    index: 321,
  },
  {
    Topic: "Heap",
    Problem: "Check if a Binary Tree is Heap",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/is-binary-tree-heap/1",
    index: 322,
  },
  {
    Topic: "Heap",
    Problem: "Connect “n” ropes with minimum cost",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes/0",
    index: 323,
  },
  {
    Topic: "Heap",
    Problem: "Convert BST to Min Heap",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/convert-bst-min-heap/",
    index: 324,
  },
  {
    Topic: "Heap",
    Problem: "Convert min heap to max heap",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/convert-min-heap-to-max-heap/",
    index: 325,
  },
  {
    Topic: "Heap",
    Problem:
      "Rearrange characters in a string such that no two adjacent are same.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0",
    index: 326,
  },
  {
    Topic: "Heap",
    Problem: "Minimum sum of two numbers formed from digits of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-sum4058/1",
    index: 327,
  },
  {
    Topic: "Graph",
    Problem: "Create a Graph, print it",
    Done: "<->",
    URL: "https://1drv.ms/t/s!AqTOHFO77CqEiRua06v1PATyiFg5",
    index: 328,
  },
  {
    Topic: "Graph",
    Problem: "Implement BFS algorithm ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1",
    index: 329,
  },
  {
    Topic: "Graph",
    Problem: "Implement DFS Algo ",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/",
    index: 330,
  },
  {
    Topic: "Graph",
    Problem: "Detect Cycle in Directed Graph using BFS/DFS Algo ",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/",
    index: 331,
  },
  {
    Topic: "Graph",
    Problem: "Detect Cycle in UnDirected Graph using BFS/DFS Algo ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1",
    index: 332,
  },
  {
    Topic: "Graph",
    Problem: "Search in a Maze",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
    index: 333,
  },
  {
    Topic: "Graph",
    Problem: "Minimum Step by Knight",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/steps-by-knight/0",
    index: 334,
  },
  {
    Topic: "Graph",
    Problem: "flood fill algo",
    Done: "<->",
    URL: "https://leetcode.com/problems/flood-fill/",
    index: 335,
  },
  {
    Topic: "Graph",
    Problem: "Clone a graph",
    Done: "<->",
    URL: "https://leetcode.com/problems/clone-graph/",
    index: 336,
  },
  {
    Topic: "Graph",
    Problem: "Making wired Connections",
    Done: "<->",
    URL: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
    index: 337,
  },
  {
    Topic: "Graph",
    Problem: "word Ladder ",
    Done: "<->",
    URL: "https://leetcode.com/problems/word-ladder/",
    index: 338,
  },
  {
    Topic: "Graph",
    Problem: "Dijkstra algo",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
    index: 339,
  },
  {
    Topic: "Graph",
    Problem: "Implement Topological Sort ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/topological-sort/1",
    index: 340,
  },
  {
    Topic: "Graph",
    Problem:
      "Minimum time taken by each job to be completed given by a Directed Acyclic Graph",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimum-time-taken-by-each-job-to-be-completed-given-by-a-directed-acyclic-graph/",
    index: 341,
  },
  {
    Topic: "Graph",
    Problem:
      "Find whether it is possible to finish all tasks or not from given dependencies",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-whether-it-is-possible-to-finish-all-tasks-or-not-from-given-dependencies/",
    index: 342,
  },
  {
    Topic: "Graph",
    Problem: "Find the no. of Islands",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1",
    index: 343,
  },
  {
    Topic: "Graph",
    Problem:
      "Given a sorted Dictionary of an Alien Language, find order of characters",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/alien-dictionary/1",
    index: 344,
  },
  {
    Topic: "Graph",
    Problem: "Implement Kruksal’sAlgorithm",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
    index: 345,
  },
  {
    Topic: "Graph",
    Problem: "Implement Prim’s Algorithm",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/",
    index: 346,
  },
  {
    Topic: "Graph",
    Problem: "Total no. of Spanning tree in a graph",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/total-number-spanning-trees-graph/",
    index: 347,
  },
  {
    Topic: "Graph",
    Problem: "Implement Bellman Ford Algorithm",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/negative-weight-cycle/0",
    index: 348,
  },
  {
    Topic: "Graph",
    Problem: "Implement Floyd warshallAlgorithm",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall/0",
    index: 349,
  },
  {
    Topic: "Graph",
    Problem: "Travelling Salesman Problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/travelling-salesman-problem-set-1/",
    index: 350,
  },
  {
    Topic: "Graph",
    Problem: "Graph ColouringProblem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/graph-coloring-applications/",
    index: 351,
  },
  {
    Topic: "Graph",
    Problem: "Snake and Ladders Problem",
    Done: "<->",
    URL: "https://leetcode.com/problems/snakes-and-ladders/",
    index: 352,
  },
  {
    Topic: "Graph",
    Problem: "Find bridge in a graph",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/bridge-in-a-graph/",
    index: 353,
  },
  {
    Topic: "Graph",
    Problem: "Count Strongly connected Components(Kosaraju Algo)",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1",
    index: 354,
  },
  {
    Topic: "Graph",
    Problem: "Check whether a graph is Bipartite or Not",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/bipartite-graph/",
    index: 355,
  },
  {
    Topic: "Graph",
    Problem: "Detect Negative cycle in a graph",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/detect-negative-cycle-graph-bellman-ford/",
    index: 356,
  },
  {
    Topic: "Graph",
    Problem: "Longest path in a Directed Acyclic Graph",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-longest-path-directed-acyclic-graph/",
    index: 357,
  },
  {
    Topic: "Graph",
    Problem: "Journey to the Moon",
    Done: "<->",
    URL: "https://www.hackerrank.com/challenges/journey-to-the-moon/problem",
    index: 358,
  },
  {
    Topic: "Graph",
    Problem: "Cheapest Flights Within K Stops",
    Done: "<->",
    URL: "https://leetcode.com/problems/cheapest-flights-within-k-stops/description/",
    index: 359,
  },
  {
    Topic: "Graph",
    Problem: "Oliver and the Game",
    Done: "<->",
    URL: "https://www.hackerearth.com/practice/algorithms/graphs/topological-sort/practice-problems/algorithm/oliver-and-the-game-3/",
    index: 360,
  },
  {
    Topic: "Graph",
    Problem: "Water Jug problem using BFS",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/water-jug-problem-using-bfs/",
    index: 361,
  },
  {
    Topic: "Graph",
    Problem: "Find if there is a path of more thank length from a source",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/",
    index: 362,
  },
  {
    Topic: "Graph",
    Problem: "M-ColouringProblem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/m-coloring-problem/0",
    index: 363,
  },
  {
    Topic: "Graph",
    Problem: "Minimum edges to reverse o make path from source to destination",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimum-edges-reverse-make-path-source-destination/",
    index: 364,
  },
  {
    Topic: "Graph",
    Problem: "Paths to travel each nodes using each edge(Seven Bridges)",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/paths-travel-nodes-using-edgeseven-bridges-konigsberg/",
    index: 365,
  },
  {
    Topic: "Graph",
    Problem: "Vertex Cover Problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/vertex-cover-problem-set-1-introduction-approximate-algorithm-2/",
    index: 366,
  },
  {
    Topic: "Graph",
    Problem: "Chinese Postman or Route Inspection",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/chinese-postman-route-inspection-set-1-introduction/",
    index: 367,
  },
  {
    Topic: "Graph",
    Problem: "Number of Triangles in a Directed and Undirected Graph",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/number-of-triangles-in-directed-and-undirected-graphs/",
    index: 368,
  },
  {
    Topic: "Graph",
    Problem:
      "Minimise the cashflow among a given set of friends who have borrowed money from each other",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/",
    index: 369,
  },
  {
    Topic: "Graph",
    Problem: "Two Clique Problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/two-clique-problem-check-graph-can-divided-two-cliques/",
    index: 370,
  },
  {
    Topic: "Trie",
    Problem: "Construct a trie from scratch",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/trie-insert-and-search/",
    index: 371,
  },
  {
    Topic: "Trie",
    Problem: "Find shortest unique prefix for every word in a given list",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/find-all-shortest-unique-prefixes-to-represent-each-word-in-a-given-list/",
    index: 372,
  },
  {
    Topic: "Trie",
    Problem: "Word Break Problem | (Trie solution)",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/word-break-problem-trie-solution/",
    index: 373,
  },
  {
    Topic: "Trie",
    Problem: "Given a sequence of words, print all anagrams together",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0",
    index: 374,
  },
  {
    Topic: "Trie",
    Problem: "Implement a Phone Directory",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/phone-directory/0",
    index: 375,
  },
  {
    Topic: "Trie",
    Problem: "Print unique rows in a given boolean matrix",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/unique-rows-in-boolean-matrix/1",
    index: 376,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Coin ChangeProblem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/coin-change2448/1",
    index: 377,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Knapsack Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0",
    index: 378,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Binomial CoefficientProblem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/ncr1019/1",
    index: 379,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Permutation CoefficientProblem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/permutation-coefficient/",
    index: 380,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Program for nth Catalan Number",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/program-nth-catalan-number/",
    index: 381,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Matrix Chain Multiplication ",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/",
    index: 382,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Edit Distance",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/edit-distance3702/1",
    index: 383,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Subset Sum Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1",
    index: 384,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Friends Pairing Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/friends-pairing-problem5425/1",
    index: 385,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Gold Mine Problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/gold-mine-problem/",
    index: 386,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Assembly Line SchedulingProblem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/assembly-line-scheduling-dp-34/",
    index: 387,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Painting the Fenceproblem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/painting-the-fence3727/1",
    index: 388,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximize The Cut Segments",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cutted-segments/0",
    index: 389,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest Common Subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0",
    index: 390,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest Repeated Subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0",
    index: 391,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest Increasing Subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-increasing-subsequence/0",
    index: 392,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Space Optimized Solution of LCS",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/space-optimized-solution-lcs/",
    index: 393,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "LCS (Longest Common Subsequence) of three strings",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/lcs-of-three-strings/0",
    index: 394,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum Sum Increasing Subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1",
    index: 395,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Count all subsequences having product less than K",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/count-subsequences-product-less-k/",
    index: 396,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest subsequence such that difference between adjacent is one",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-subsequence-such-that-difference-between-adjacents-is-one4724/1",
    index: 397,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum subsequence sum such that no three are consecutive",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-subsequence-sum-such-that-no-three-are-consecutive/",
    index: 398,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Egg Dropping Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0",
    index: 399,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum Length Chain of Pairs",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/max-length-chain/1",
    index: 400,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum size square sub-matrix with all 1s",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/largest-square-formed-in-a-matrix/0",
    index: 401,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum sum of pairs with specific difference",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/pairs-with-specific-difference/0",
    index: 402,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Min Cost PathProblem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/path-in-matrix3805/1",
    index: 403,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum difference of zeros and ones in binary string",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-difference-of-zeros-and-ones-in-binary-string4111/1",
    index: 404,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Minimum number of jumps to reach end",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
    index: 405,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Minimum cost to fill given weight in a bag",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-cost-to-fill-given-weight-in-a-bag1956/1",
    index: 406,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Minimum removals from array to make max –min <= K",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/minimum-removals-array-make-max-min-k/",
    index: 407,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest Common Substring",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-common-substring/0",
    index: 408,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Count number of ways to reacha given score in a game",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/reach-a-given-score/0",
    index: 409,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Count Balanced Binary Trees of Height h",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/bbt-counter/0",
    index: 410,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "LargestSum Contiguous Subarray [V>V>V>V IMP ]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
    index: 411,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Smallest sum contiguous subarray",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/smallest-sum-contiguous-subarray/",
    index: 412,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Unbounded Knapsack (Repetition of items allowed)",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/knapsack-with-duplicate-items4201/1",
    index: 413,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Word Break Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/word-break/0",
    index: 414,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Largest Independent Set Problem",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/largest-independent-set-problem-dp-26/",
    index: 415,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Partition problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1",
    index: 416,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest Palindromic Subsequence",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/",
    index: 417,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Count All Palindromic Subsequence in a given String",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1",
    index: 418,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest Palindromic Substring",
    Done: "<->",
    URL: "https://leetcode.com/problems/longest-palindromic-substring/",
    index: 419,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Longest alternating subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-alternating-subsequence/0",
    index: 420,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Weighted Job Scheduling",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/weighted-job-scheduling/",
    index: 421,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Coin game winner where every player has three choices",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/coin-game-winner-every-player-three-choices/",
    index: 422,
  },
  {
    Topic: "Dynamic Programming",
    Problem:
      "Count Derangements (Permutation such that no element appears in its original position) [ IMPORTANT ]",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/count-derangements-permutation-such-that-no-element-appears-in-its-original-position/",
    index: 423,
  },
  {
    Topic: "Dynamic Programming",
    Problem:
      "Maximum profit by buying and selling a share at most twice [ IMP ]",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
    index: 424,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Optimal Strategy for a Game",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/optimal-strategy-for-a-game/0",
    index: 425,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Optimal Binary Search Tree",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/optimal-binary-search-tree-dp-24/",
    index: 426,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Palindrome PartitioningProblem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/palindromic-patitioning4845/1",
    index: 427,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Word Wrap Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/word-wrap/0",
    index: 428,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Mobile Numeric Keypad Problem [ IMP ]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/mobile-numeric-keypad5456/1",
    index: 429,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Boolean Parenthesization Problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/boolean-parenthesization/0",
    index: 430,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Largest rectangular sub-matrix whose sum is 0",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/largest-rectangular-sub-matrix-whose-sum-0/",
    index: 431,
  },
  {
    Topic: "Dynamic Programming",
    Problem:
      "Largest area rectangular sub-matrix with equal number of 1’s and 0’s [ IMP ]",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/largest-area-rectangular-sub-matrix-equal-number-1s-0s/",
    index: 432,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum sum rectangle in a 2D matrix",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-sum-rectangle/0",
    index: 433,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum profit by buying and selling a share at most k times",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-profit4657/1",
    index: 434,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Find if a string is interleaved of two other strings",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/interleaved-strings/1",
    index: 435,
  },
  {
    Topic: "Dynamic Programming",
    Problem: "Maximum Length of Pair Chain",
    Done: "<->",
    URL: "https://leetcode.com/problems/maximum-length-of-pair-chain/",
    index: 436,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Count set bits in an integer",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/set-bits0143/1",
    index: 437,
  },
  {
    Topic: "Bit Manipulation",
    Problem:
      "Find the two non-repeating elements in an array of repeating elements",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/finding-the-numbers0215/1",
    index: 438,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Count number of bits to be flipped to convert A to B",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/bit-difference/0",
    index: 439,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Count total set bits in all numbers from 1 to n",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-total-set-bits/0",
    index: 440,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Program to find whether a no is power of two",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/power-of-2/0",
    index: 441,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Find position of the only set bit",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/find-position-of-set-bit3706/1",
    index: 442,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Copy set bits in a range",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/copy-set-bits-in-a-range/",
    index: 443,
  },
  {
    Topic: "Bit Manipulation",
    Problem:
      "Divide two integers without using multiplication, division and mod operator",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/divide-two-integers-without-using-multiplication-division-mod-operator/",
    index: 444,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Calculate square of a number without using *, / and pow()",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/",
    index: 445,
  },
  {
    Topic: "Bit Manipulation",
    Problem: "Power Set",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/power-set4302/1",
    index: 446,
  },
];

export default data;
